doctrine_migrations:
    migrations_paths:
        Application\Migrations: 'db/DoctrineMigrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_length: 255
