language: php

php:
  - 7.1
  - 7.2

env:
  - DB=mysql

before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_38f96163e3a4_key -iv $encrypted_38f96163e3a4_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-docutils openjdk-7-jre

before_script:
  - if [ "$DB" == "mysql" ]; then mysql -e "create database phpofby DEFAULT CHARACTER SET utf8 ; grant all on phpofby.* to 'symfony'@'localhost' identified by 'symfony';" -uroot; fi
  - phpenv config-add travis.php.ini

script:
  - php phing.phar build-ci

addons:
  ssh_known_hosts: php.of.by

before_deploy: "export SYMFONY_ENV=prod && php phing.phar package && unset SYMFONY_ENV"

deploy:
  provider: script
  script: ./bin/deploy-to-prod.sh
  skip_cleanup: true
  on:
      tags: true
