language: php

os: [linux]

dist: focal

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - node_modules

php:
  - 8.1

services:
  - mysql

before_install:
  - nvm install 18
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_38f96163e3a4_key -iv $encrypted_38f96163e3a4_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d; fi
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-docutils yarn

before_script:
  - mysql -e "CREATE DATABASE phpofby DEFAULT CHARACTER SET utf8; CREATE USER 'symfony'@'localhost' identified by 'symfony'; GRANT ALL ON phpofby.* TO 'symfony'@'localhost'" -uroot

script:
  - php phing.phar build-ci

addons:
  ssh_known_hosts: php.of.by

before_deploy: "php phing.phar package"

deploy:
  provider: script
  script: ./bin/deploy-to-prod.sh
  skip_cleanup: true
  on:
      tags: true
