imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    assets_version: v=3
    project_name: php.of.by
    project_version: "~PROJECT_VERSION~"
    fos_user_bundle_user_class: PhpOfBy\SecurityBundle\Entity\User

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets:
        # set version of assets to simplify cache flushing
        version: '%assets_version%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project_name: '%project_name%'
        project_version: '%project_version%'
        google_analytics_id: '%google_analytics_id%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Assetic configuration
assetic:
    filters:
        lessphp:
            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"
            apply_to: "\\.less$"
    assets:
        common_css:
            inputs:
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/general.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/buttons.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/grid.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/headings.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/icons.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/forms.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/navbar.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/tables.less"
                - "%kernel.root_dir%/../vendor/owenversteeg/min/less/messages.less"
                - "@PhpOfByWebsiteBundle/Resources/public/css/common.css"
            output: css/common.css
        index_css:
            inputs:
                - "@PhpOfByWebsiteBundle/Resources/public/css/front.css"
            output: css/front.css

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine extensions configuration
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

fos_user:
    db_driver: orm
    firewall_name: webui_secured
    user_class: '%fos_user_bundle_user_class%'
    service:
      user_manager: phpofby_security.service.user

easy_admin:
    entities:
        User:
            class: '%fos_user_bundle_user_class%'
            list:
                fields: ['username', 'email', 'enabled', 'lastLogin', 'locked', 'createdAt', 'updatedAt']
            new:
                fields:
                    - 'enabled'
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: 'text', label: 'Password' }
                    - 'roles'
                    - 'lastLogin'
            edit:
                fields:
                      - 'enabled'
                      - 'username'
                      - 'email'
                      - { property: 'plainPassword', type: 'text', label: 'Password', type_options: { required: false }}
                      - 'roles'
                      - 'lastLogin'
