assetic:
    debug:          false
    use_controller: false
    bundles:
      - PhpOfByWebsiteBundle
    filters:
      yui_css:
        jar: '%kernel.root_dir%/Resources/java/yuicompressor/yuicompressor-2.4.8.jar'
        apply_to: '\\.css$'
