parameters:
  phpofby_website.controller.default.class: PhpOfBy\WebsiteBundle\Controller\DefaultController

services:
  phpofby_website.controller.default:
    class: '%phpofby_website.controller.default.class%'
    parent: common.contoller.abstract
    public: true
    arguments: []
