easy_admin:
    entities:
        User:
            class: '%fos_user_bundle_user_class%'
            list:
                fields: ['username', 'email', 'enabled', 'lastLogin', 'createdAt', 'updatedAt']
            new:
                fields:
                    - 'enabled'
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: 'text', label: 'Password' }
                    - { property: 'roles', type: 'PhpOfBy\SecurityBundle\Form\Type\RolesChoiceType' }
            edit:
                fields:
                      - 'enabled'
                      - 'username'
                      - 'email'
                      - { property: 'plainPassword', type: 'text', label: 'Password', type_options: { required: false }}
                      - { property: 'roles', type: 'PhpOfBy\SecurityBundle\Form\Type\RolesChoiceType' }
                      - { property: 'lastLogin', type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType', type_options: { widget: 'single_text', attr: {readonly: true}}}
        Article:
            class: 'PhpOfBy\ContentBundle\Entity\Article'
            list:
                fields: ['articleId', 'published', 'title', 'publicationDate', 'createdAt', 'updatedAt']
            form:
                fields:
                    - 'published'
                    - 'title'
                    - 'publicationDate'
                    - { property: 'teaser', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                    - { property: 'body', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
