easy_admin:
    entities:
        User:
            class: '%fos_user_bundle_user_class%'
            list:
                fields: ['username', 'email', 'enabled', 'lastLogin', 'createdAt', 'updatedAt']
            new:
                fields:
                    - 'enabled'
                    - 'username'
                    - 'email'
                    - { property: 'plainPassword', type: 'text', label: 'Password' }
                    - 'roles'
                    - 'lastLogin'
            edit:
                fields:
                      - 'enabled'
                      - 'username'
                      - 'email'
                      - { property: 'plainPassword', type: 'text', label: 'Password', type_options: { required: false }}
                      - 'roles'
                      - 'lastLogin'
        Article:
            class: 'PhpOfBy\ContentBundle\Entity\Article'
            list:
                fields: ['articleId', 'published', 'title', 'publicationDate', 'createdAt', 'updatedAt']
            form:
                fields:
                    - 'published'
                    - 'title'
                    - 'publicationDate'
                    - { property: 'teaser', type: 'ckeditor' }
                    - { property: 'body', type: 'ckeditor' }
