fos_user:
    from_email:
      address: '%mailer_user%'
      sender_name: '%mailer_user%'
    db_driver: orm
    firewall_name: main
    user_class: '%fos_user_bundle_user_class%'
    service:
      mailer: fos_user.mailer.noop
      user_manager: phpofby_security.service.user
