parameters:
  phpofby_security.service.user.class: PhpOfBy\SecurityBundle\Service\UserManagerServiceDoctrineOrm

services:
  phpofby_security.service.user:
    class: '%phpofby_security.service.user.class%'
    lazy: true
    arguments:
      - '@fos_user.util.password_updater'
      - '@fos_user.util.canonical_fields_updater'
      - '@fos_user.object_manager'
      - '%fos_user.model.user.class%'
