parameters:
  phpofby_security.service.user.class: PhpOfBy\SecurityBundle\Service\UserManagerServiceDoctrineOrm

services:
  phpofby_security.service.user:
    parent: fos_user.user_manager.default
    class: '%phpofby_security.service.user.class%'
    lazy: true
